app/responses/__init__.py
from flask import Blueprint

bp = Blueprint("responses", __name__)

from app.responses import routes

app/responses/routes.py
from statistics import mean

from bokeh.models.formatters import FuncTickFormatter
from bokeh.models.tickers import FixedTicker
from flask import redirect
from flask import request
from flask.helpers import flash, send_file, url_for
from flask_login import current_user, login_required
from flask.templating import render_template
from munch import munchify
from sqlalchemy import desc
from werkzeug.exceptions import HTTPException

from app import db
from app.admin.decorators import valid_admin_required, admin_required
from app.models import Card, DataValueLabel, Response, Study, Response
from app.responses import bp
from app.responses.parsing.add_heat_maps import (
    CreateOneHeatMap,
    CreateOneHeatMapCount,
)
from app.responses.parsing.average_response2 import average_response as avg
from app.responses.parsing.create_pdf import create_pdf as gen_pdf
from app.responses.parsing.position_count import (
    get_card_x_responses,
    get_card_y_responses,
)



@bp.route("/<int:id>")
@login_required
@admin_required
@valid_admin_required(model="study")
def general(id, study):
    script_x, div_x = get_card_x_responses(study)
    script_y, div_y = get_card_y_responses(study)

    return render_template(
        "responses/general.html",
        plot_script_x=script_x,
        plot_div_x=div_x,
        plot_script_y=script_y,
        plot_div_y=div_y,
        responses=study.responses,
        study=study,
    )


@bp.route("/heat_maps/<int:id>", methods=["GET", "POST"])
@login_required
@admin_required
@valid_admin_required(model="study")
def heat_maps(id, study):

    if request.method == "POST":
        data = request.get_json()
        if data.get("type") == "one":

            card_x = Card.query.filter_by(id=data.get("card_x_id")).first()
            card_y = Card.query.filter_by(id=data.get("card_y_id")).first()

            if data.get("label_id"):
                hm = CreateOneHeatMap(study)
                data_value_label = DataValueLabel.query.filter_by(
                    id=data.get("label_id")
                ).first()

                hm.add(
                    card_x=card_x, card_y=card_y, data_value_label=data_value_label,
                )
            else:
                hm = CreateOneHeatMapCount(study)
                hm.add(
                    card_x=card_x, card_y=card_y, data_value_label=None,
                )

        return dict(plots=dict(hm.plots))

    return render_template(
        "responses/heat_maps.html",
        study=study,
        card_set_x=study.card_set_x,
        card_set_y=study.card_set_y,
    )


@bp.route("/compare/<int:id>", methods=["GET", "POST"])
@login_required
@admin_required
@valid_admin_required(model="study")
def compare_responses(id, study):
    if request.method == "POST":
        data = request.get_json()

        if data.get("response_id_1") == "average":
            response_1 = avg(study)
        else:
            response_1 = Response.query.filter(
                Response.study == study, Response.id == int(data.get("response_id_1")),
            ).first()

        if data.get("response_id_2") == "average":
            response = avg(study)
        else:
            response = Response.query.filter(
                Response.study == study, Response.id == int(data.get("response_id_2")),
            ).first()
        data = render_template(
            "responses/response.html", study=study, responses=[response_1, response],
        )
        return dict(data=data)

    return render_template("responses/compare_responses.html", study=study)


@bp.route("/average/<int:id>")
@login_required
@admin_required
@valid_admin_required(model="study")
def average_response(id, study):

    avg_response = avg(study)
    return render_template(
        "responses/average_response.html", study=study, responses=[avg_response]
    )


@bp.route("/create_pdf/<int:id>", methods=["GET", "POST"])
@login_required
@admin_required
@valid_admin_required(model="study")
def create_pdf(id, study):

    if request.method == "POST":
        try:
            data = request.get_json()
            file_path = gen_pdf(
                study,
                all_responses=data.get("all_responses"),
                average_response2=data.get("average_response"),
                response_ids=data.get("response_ids"),
            )
            return dict(file_path=file_path)
        except:
            flash("Could not create pdf.")

    return render_template(
        "/responses/create_pdf.html", study=study, responses=study.responses
    )

app/templates/responses/average_response.html
{% extends "responses/responses_base.html" %}
{% block head %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='css/board.css') }}">
{% endblock %}
{% block content %}
{{ super() }}
<h3>Average Response</h3>
<p>This shows the average position for each card and average value for 
    all data value label for all current responses to the study <b>{{ study.name }}</b>.</p>

{% endblock %}
{% block table %}
{{ super() }}
{% include "responses/response.html" %}
{% endblock %}

app/templates/responses/compare_responses.html
{% extends "responses/responses_base.html" %}

{% block head %}
{{ super() }}
<script src="{{ url_for('static', filename='js/compare_responses.js') }}"></script>
<link rel="stylesheet" href="{{ url_for('static', filename='css/board.css') }}">
{% endblock %}

{% block content %}
<h3>Compare Responses</h3>
<p>Here you can compare responses to study <b>{{ study.name }}</b> from pairs of users.</p>
<form>
    <div class="form-row">
        <div class="form-group col-md-3">
            <label>Response 1</label>
            <select id="response-1" class="form-control" csrf_token="{{ csrf_token() }}">
                <option response_id="average">Average</option>
                {% for response in study.responses %}
                    <option response_id="{{ response.id }}">{{ response.participant.username }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group col-md-3">
            <label>Response 2</label>
            <select id="response-2" class="form-control" csrf_token="{{ csrf_token() }}">
                    <option response_id="average">Average</option>
                {% for response in study.responses %}
                    <option response_id="{{ response.id }}">{{ response.participant.username }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group col-md-6 align-self-end text-white">
            <a class="btn btn-primary compare-responses" url="{{ url_for('responses.compare_responses', id=study.id) }}" csrf_token="{{ csrf_token() }}">Compare</a>
            <a id="remove-all" class="btn btn-danger">Remove All</a>
        </div>
    </div>
</form>
{% endblock %}
{% block table %}
<div class="row responses">

</div>
{% endblock %}

app/templates/responses/create_pdf.html
{% extends "responses/responses_base.html" %}

{% block head %}
{{ super() }}
<script src="{{ url_for('static', filename='js/create_pdf.js') }}"></script>
{% endblock %}

{% block content %}
<h3>Create PDF</h3>
<p>Here you can generate a PDF and select what responses you want to include in the pdf</p>
<form>
    <div class="form-row">
        <div class="form-group">
            <div class="custom-control custom-checkbox all-responses">
                <input id="all-responses" type="checkbox" class="custom-control-input" >
                <label class="custom-control-label" for="all-responses">All Responses</label>
            </div>
        </div>
        <div class="form-group">
            <div class="custom-control custom-checkbox">
                <input id="average-response" type="checkbox" class="custom-control-input" >
                <label class="custom-control-label" for="average-response">Average Response</label>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label for="specific-responses">Specific Responses</label>
        <select multiple class="form-control specific-responses" id="specific-responses">
            {% for response in responses %}
                <option response_id="{{ response.id }}">{{ response.participant.username }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="form-group text-white">
        <a class="btn btn-primary create-pdf" url="{{ url_for('responses.create_pdf', id=study.id) }}" csrf_token="{{ csrf_token() }}">Download PDF</a>
    </div>
</form>
{% endblock %}

app/templates/responses/general.html
{% extends "responses/responses_base.html" %}


{% block head %}
    {{ super() }}
    {{ plot_script_x|indent(4)|safe }}
    {{ plot_script_y|indent(4)|safe }}
    {% for script_heatmap in heatmap_plots %}
        {{ script_heatmap[0]|indent(4)|safe }}
    {% endfor %}
{% endblock %}
{% block content %}
<h3>General</h3>
    <div class="row">
        <div class="col text-center">
            <h4>{{ responses|length }} Responses</h4>
        </div>
    </div>
    <div class="row">
        <div class="col-xs">
            {{ plot_div_x|indent(4)|safe }}
        </div>
    </div>
    <div class="row">
        <div class="col-xs">
            {{ plot_div_y|indent(4)|safe }}
        </div>
    </div>    

    
{% endblock %}

app/templates/responses/heat_maps.html
{% extends "responses/responses_base.html" %}

{% block head %}
{{ super() }}
<script src="{{ url_for('static', filename='js/heatmaps.js') }}"></script>
<link rel="stylesheet" href="{{ url_for('static', filename='css/heat_maps.css') }}">
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>

{% endblock %}

{% block content %}
{{super()}}
<h3>Heat Maps</h3>
<p>Here you can add individual heat maps of pairings of cards from card set 
    <b>{{ card_set_x.name }}</b> and card set <b>{{ card_set_y.name }}</b> 
    over different data value labels from study <b>{{ study.name }}</b> </p>
<form>
    <div class="form-row">
        <div class="form-group col-md-3">
            <label>{{ card_set_x.name }}</label>
            <select id="card-x" class="form-control">
                {% for card_x in card_set_x.cards %}
                    <option card_id="{{ card_x.id }}">{{ card_x.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group col-md-3">
            <label>{{ card_set_y.name }}</label>
            <select id="card-y" class="form-control">
                
                {% for card_y in card_set_y.cards %}
                    <option card_id="{{ card_y.id }}">{{ card_y.name }}</option>
                {% endfor %}
            </select>
        </div>
        {% if study.data_value_labels|length > 0 %}
            <div class="form-group col-md-3">
                <label>Data Value Label</label>
                <select id="label" class="form-control">
                    {% for label in study.data_value_labels %}
                        <option label_id="{{ label.id }}">{{ label.label }}</option>
                    {% endfor %}
                </select>
            </div>
        {% endif %}
        <div class="form-group col-md-3">
            <label>Type</label>
            <select id="type" class="form-control">
                <option type="true">Count</option>
                {% if study.data_value_labels|length > 0 %}
                    <option type="false">Not Count</option>
                {% endif %}
            </select>
        </div>
        
        <div class="form-group col-md-6 align-self-end text-white">
            <a class="btn btn-primary add-heatmap" url="{{ url_for('responses.heat_maps', id=study.id) }}" csrf_token="{{ csrf_token() }}" type="one">Add</a>
            <a id="remove-all-heatmaps" class="btn btn-danger">Remove All</a>
        </div>
        
        
    </div>
</form>
<div class="row loading">
    
</div>
<div class="row heat-map-grid">
    
</div>
{% endblock %}

app/templates/responses/index.html
{% extends "base.html" %}

{% block content %}
    {% if studies %}
    <div class="row">
    {% for study in studies %}
    
        <div class="col-sm-6">
                <div class="card">
                  {% if study.image %}
                      <img style="width: 100%; height: 13vw; object-fit: cover;" class="card-img-top" src="{{ url_for('static', filename='img/study_images/'~creator~'/'+study.image) }}" alt="Study Image">
                  {% else %}
                      <img style="width: 100%; height: 13vw; object-fit: cover;" src="{{url_for('static', filename='img/study_images/no_image.jpg')}}" class="card-img-top" alt="No Image">
                  {% endif %}
                  <div class="card-body">
  
                    <h5 class="card-title">{{ study.name }}</h5>
                    <h6 class="card-subtitle mb-2 text-muted">{{ study.start_date }} to {{ study.end_date }}</h6>
                    {% if study.description %}
                      <p class="card-text">{{ study.description }}</p>
                    {% endif %}
                    
                      <a class="btn btn-primary btn-sm" href="{{ url_for('responses.general', id=study.id) }}">View Responses</a>
                    </div>
                </div>
                </div>
        {% endfor %}
        </div>
    {% else %}
    {% endif %}
{% endblock %}

app/templates/responses/response.html
{% if responses|length > 0 %}
    {% for response in responses %}
        {% if response.participant.username %}
            <h3>{{ response.participant.username }}'s response</h3>
        {% else %}
            <h3>Average Response</h3>
        {% endif %}
        <div id="card-table" class="table-responsive">
            <table class="table table-bordered">
                {% for row in range(study.number_of_rows) %}
                {% set row_loop = loop %}
                <tr>
                       <td style="border:none;" class="sortable-y droptrue2 cards-row">
                        {% for card_position in response.card_positions %}
                            {% if card_position.card.card_set == study.card_set_y %}
                                {% if card_position.position == study.number_of_rows-row_loop.index %}
                                    <div>
                                        <div class="card">
                                            {% if card_position.card.image %}
                                                <img class="card-img-top" src="{{ url_for('static', filename='img/card_images/'+study.creator_id|string+'/'+card_position.card.image) }}" alt="Card Image">
                                            {% endif %}
                                            <div class="card-body">
                                                {% if card_position.card.description %}
                                                <p class="card-text" data-toggle="tooltip" data-placement="top" title="{{ card_position.card.description }}">{{ card_position.card.name }}</p>       
                                                {% else %}
                                                    <p class="card-text">{{ card_position.card.name }}</p>
                                                {% endif %}
                                            </div>
                                        </div>
                                    </div>
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                            
                        </td>
                        {% if loop.index0 == 0%}
                            <td style="border:none; vertical-align:middle">
                                <p>Highest {{ study.card_set_y.measure}} </p>
                            </td>
                        {% elif loop.index0 == study.number_of_rows-1 %}
                            <td style="border:none; vertical-align:middle">
                                <p>Lowest {{ study.card_set_y.measure }}</p>
                            </td>
                        {% else %}
                            <td style="border:none;"></td>
                        {% endif%}
                           
                        {% for column in range(0,study.number_of_columns) %}
                        
                        <td style="vertical-align: middle;">
                            {% for data_value in response.data_values %}
                        
                    
                                {% if data_value.column == column and data_value.row == study.number_of_rows-row_loop.index %}
                                    
                                        
                                        <form>
                                            <div class="form-group">
                                                <label>{{ data_value.data_value_label.label }}</label>
                                                <input type="number"  class="data_values form-control form-control-sm" value="{{ data_value.value }}">    
                                            </div>
                                        </form>
                                {% endif %} 
                            {% endfor %}
                        </td>
    
                        {% endfor %}
                    </tr>
                {% endfor %}
               <tr>
                   <td style="border: none;">
                   </td>
                   <td style="border:none;">
                   </td>
                   
                   {% for col in range(0, study.number_of_columns) %}
                   {% if loop.index0==0 %}
                       <td style="border:none; text-align:center;">
                           Lowest {{ study.card_set_x.measure }}
                       </td>
                   {% elif loop.index0 == study.number_of_columns-1 %}
                       <td style="border:none; text-align:center;">
                           Highest {{ study.card_set_x.measure }}
                       </td>
                   {% else %}
                       <td style="border:none;"></td>
                   {% endif %}
                   {% endfor %}
               </tr>
               <tr>
                    <td style="border: none;">
                    </td>
                    <td style="border: none;">
                    </td>
                    {% for column in range(study.number_of_columns) %}
                        <td style="border:none;" class="sortable-x droptrue1 cards-col">
                            {% for card_position in response.card_positions %}
                                {% if (card_position.card.card_set == study.card_set_x) and (card_position.position == column) %}
                                        <div>
                                            <div class="card">
                                                {% if card_position.card.image %}
                                                    <img class="card-img-top" src="{{ url_for('static', filename='img/card_images/'+study.creator_id|string+'/'+card_position.card.image) }}" alt="Card Image">
                                                {% endif %}
                                                <div class="card-body">
                                                    {% if card_position.card.description %}
                                                        <p class="card-text" data-toggle="tooltip" data-placement="top" title="{{ card_position.card.description }}">{{ card_position.card.name }}</p>       
                                                    {% else %}
                                                        <p class="card-text">{{ card_position.card.name }}</p>
                                                    {% endif %}
                                                </div>
                                            </div>
                                        </div>
                                {% endif %}
                            {% endfor %}
                        </td>
                    {% endfor %}
               </tr>
            </table>
        </div>
    {% endfor %}
{% endif %}

app/templates/responses/responses_base.html
{% extends "base.html" %}

{% block head %}
<link rel="stylesheet" href="http://cdn.bokeh.org/bokeh/release/bokeh-1.4.0.min.css" type="text/css" />
<script type="text/javascript" src="http://cdn.bokeh.org/bokeh/release/bokeh-1.4.0.min.js"></script>
<script src="{{ url_for('static', filename='js/active_link.js') }}"></script>
{% endblock %}

{% block subnav %}
<nav class="nav bg-light">
    <a class="nav-link active" href="{{ url_for('responses.general', id=study.id) }}">General</a>
    <a class="nav-link" href="{{url_for('responses.heat_maps', id=study.id) }}">Heat Maps</a>
    <a class="nav-link" href="{{url_for('responses.compare_responses', id=study.id) }}">Compare Responses</a>
    <a class="nav-link" href="{{url_for('responses.average_response', id=study.id) }}">Average Response</a>
    <a class="nav-link" href="{{url_for('responses.create_pdf', id=study.id) }}">Create PDF</a>
</nav>
{% endblock %}
{% block content %}
{% endblock %}
{% block table %}
{% endblock %}