app/study/forms.py
import json

from flask import url_for
from flask_wtf import FlaskForm
from wtforms import SubmitField, SelectField
from wtforms.validators import DataRequired

# f_age_groups = open(url_for('static', filename='json/age_groups.json'))
f_age_groups = open("app/static/json/age_groups.json")
data = json.load(f_age_groups)
data_age_groups = [(k, v) for k, v in data.items()]
f_age_groups.close()

# f_countries = open(url_for('static', filename='json/countries.json'))
f_countries = open("app/static/json/countries.json")
data = json.load(f_countries)
data_countries = [(k, v) for k, v in data.items()]
f_countries.close()

# f_educations = open(url_for('static', filename='json/educations.json'))
f_educations = open("app/static/json/educations.json")
data = json.load(f_educations)
data_educations = [(k, v) for k, v in data.items()]
f_educations.close()

# f_genders = open(url_for('static', filename='json/genders.json'))
f_genders = open("app/static/json/genders.json")
data = json.load(f_genders)
data_genders = [(k, v) for k, v in data.items()]
f_genders.close()

# f_incomes = open(url_for('static', filename='json/incomes.json'))
f_incomes = open("app/static/json/incomes.json")
data = json.load(f_incomes)
data_incomes = [(k, v) for k, v in data.items()]
f_incomes.close()

# f_occupations = open(url_for('static', filename='json/occupations.json'))
f_occupations = open("app/static/json/occupations.json")
data = json.load(f_occupations)
data_occupations = [(k, v) for k, v in data.items()]
f_occupations.close()


class UserInfoForm(FlaskForm):
    gender = SelectField("Gender", choices=data_genders, validators=[DataRequired()])
    age_group = SelectField(
        "Age Group", choices=data_age_groups, validators=[DataRequired()]
    )
    nationality = SelectField(
        "Country of Birth", choices=data_countries, validators=[DataRequired()]
    )
    latest_country = SelectField(
        "Latest Country", choices=data_countries, validators=[DataRequired()]
    )
    education_level = SelectField(
        "Education Level", choices=data_educations, validators=[DataRequired()]
    )
    occupation = SelectField(
        "Occupation", choices=data_occupations, validators=[DataRequired()]
    )
    income = SelectField("Income", choices=data_incomes, validators=[DataRequired()])
    submit = SubmitField("Submit")

app/study/__init__.py
from flask import Blueprint

bp = Blueprint("study", __name__)

from app.study import routes

app/study/routes.py
from datetime import date
import itertools

from flask import render_template, flash, redirect, url_for, request
from flask_login import current_user, login_required
from werkzeug.wrappers import Response as WrkResponse
from munch import munchify

from app import db
from app.models import (
    CardSet,
    Response,
    Study,
    CardPosition,
    DataValue,
    DataValueLabel,
    Response,
    Card,
)
from app.study import bp
from app.study.decorators import *
from app.study.forms import UserInfoForm
from app.study.helpers import convert_response


@bp.route("/index")
@bp.route("/")
@login_required
@participant_required
@completed_info_form_required
@check_complete_study
def index():
    return render_template("study/index.html", study=current_user.user_group.study)


@bp.route("/<int:id>", methods=["GET", "POST"])
@login_required
@participant_required
@valid_participant_required
@completed_info_form_required
@check_complete_study
def study(id, study):

    if request.method == "POST":
        data = request.get_json()

        cards_x = data.get("cards_x")
        cards_y = data.get("cards_y")
        data_values = data.get("data_values")

        response = convert_response(cards_x, cards_y, data_values)
        response.study = study
        response.participant = current_user

        db.session.add(response)
        current_user.completed_study = True
        db.session.commit()

        return dict(url=url_for("study.complete"))

    return render_template(
        "study/study.html",
        study=study,
        card_set_x=study.card_set_x,
        card_set_y=study.card_set_y,
        creator_id=study.creator_id,
    )


@bp.route("/user_info", methods=["POST", "GET"])
@login_required
@participant_required
@check_complete_study
def user_info():
    form = UserInfoForm()
    if form.validate_on_submit():
        current_user.gender = form.gender.data
        current_user.age_group = form.age_group.data
        current_user.country_of_birth = form.nationality.data
        current_user.education_level = form.education_level.data
        current_user.occupation = form.occupation.data
        current_user.latest_country = form.latest_country.data
        current_user.income = form.income.data
        current_user.completed_form = True
        try:
            db.session.commit()
            return redirect(url_for("study.index"))
        except:
            flash("There was a problem submitting your information. Please try again.")
            db.session.rollback()
    if request.method == "GET":
        form.gender.data = current_user.gender
        form.age_group.data = current_user.age_group
        form.nationality.data = current_user.country_of_birth
        form.education_level.data = current_user.education_level
        form.occupation.data = current_user.occupation
        form.latest_country.data = current_user.latest_country
        form.income.data = current_user.income
    return render_template("study/user_info.html", form=form)


@bp.route("/change_info", methods=["POST", "GET"])
@login_required
@participant_required
@completed_info_form_required
@check_complete_study
def change_info():
    form = UserInfoForm()

    if form.validate_on_submit():
        current_user.gender = form.gender.data
        current_user.age_group = form.age_group.data
        current_user.country_of_birth = form.nationality.data
        current_user.education_level = form.education_level.data
        current_user.occupation = form.occupation.data
        current_user.latest_country = form.latest_country.data
        current_user.income = form.income.data
        current_user.completed_form = True
        try:
            db.session.commit()
            return redirect(url_for("study.index"))
        except:
            flash("There was a problem submitting your information. Please try again.")
            db.session.rollback()
    if request.method == "GET":
        form.gender.data = current_user.gender
        form.age_group.data = current_user.age_group
        form.nationality.data = current_user.country_of_birth
        form.education_level.data = current_user.education_level
        form.occupation.data = current_user.occupation
        form.latest_country.data = current_user.latest_country
        form.income.data = current_user.income

    return render_template("study/change_user_info.html", form=form)


@bp.route("/complete")
@login_required
@participant_required
@completed_info_form_required
@check_not_completed_study
def complete():
    return render_template("study/complete.html")

app/templates/study/change_user_info.html
{% extends "base.html" %}
{% block content %}
<h3>Edit User Info</h3>
<p>Change user info you previously enterered. You will not be able to change this after you have finished the study and logged out.</p>
{% include "study/info_form_base.html" %}
{% endblock %}

app/templates/study/complete.html
{% extends "base3.html" %}

{% block content %}
<div class="row h-100 justify-content-center align-items-center">
    
            
    <div class="text-center">
        {% with messages = get_flashed_messages() %}
                {% if messages %}
                <div class="alert alert-primary" role="alert">
                        {% for message in messages %}
                            {{ message }}
                        {% endfor %}
                </div>
                {% endif %}
        {% endwith %}
        <h3>Thank You!</h3>
        <p>Thanks for participating in the study, you can now log out of the system.</p>
        <a href="{{ url_for('auth.logout') }}" class="btn btn-primary btn-sm">Log out</a> 
    </div>
</div>
{% endblock %}

app/templates/study/how_to.html
{% extends "base.html" %}

{% block content %}
<h3>How To</h3>
<p>Below is a video to help you to answer the study as it is not entirely obvious.</p>
<div class="row">
    <div class="col-sm-6">
      <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="//www.youtube.com/embed/zB4I68XVPzQ"></iframe>
      </div>
    </div>
</div>
<a style="margin-top:20px;" class="btn btn-primary" href="{{ url_for('study.index') }}" role="button">Go to Study</a>

{% endblock %}

app/templates/study/index.html
{% extends "base.html" %}
{% block head %}
<script src="{{ url_for('static', filename='js/play_video.js') }}"></script>

{% endblock %}
{% block content %}
{% if study %}
    <h3>Your Study To Complete</h3>
    <div class="row row-cols-2">
        <div class="col-sm-6">
            <div class="card">
                {% if study.image %}
                    <img style="width: 100%; height: 13vw; object-fit: cover;" class="card-img-top" src="{{ url_for('static', filename='img/study_images/'+study.creator.id|string+'/'+study.image) }}" alt="Study Image">
                {% else %}
                    <img style="width: 100%; height: 13vw; object-fit: cover;" src="{{url_for('static', filename='img/study_images/no_image.jpg')}}" class="card-img-top" alt="No Image">
                {% endif %}
                <div class="card-body">
                    <h5 class="card-title">{{ study.name }}</h5>
                    {% if study.description %}
                        <p class="card-text">{{ study.description }}</p>
                    {% endif %}
                    <p class="card-text">You have until the end of <b>{{ study.end_date }}</b> to complete this
                        study.</p>
                    <button type="button" class="btn btn-primary btn-sm video-btn" data-toggle="modal" data-src="https://www.youtube.com/embed/HDgNzhMN1sU" data-target="#video-{{study.id}}-modal">
                        Start Study
                    </button>
                </div>
            </div>
        </div>
        <div class="modal fade" id="video-{{study.id}}-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-xl" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <p class="modal-body">Below shows a video on how to complete the study. Please watch it before starting the study.</p>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                    <div class="modal-body"> 
                        <div class="embed-responsive embed-responsive-16by9">
                            <iframe class="embed-responsive-item" src="" id="video"  allowscriptaccess="always" allow="autoplay" allowfullscreen></iframe>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <a href="{{ url_for('study.study', id=study.id ) }}" class="btn btn-primary btn-sm">Continue to Study</a> 
                    </div>
            
                </div>
            </div>
        </div> 
    </div>
{% endif %}
{% endblock %}

app/templates/study/info_form_base.html
<form action="" method="post" novalidate>
    {{ form.hidden_tag() }}
    <div class="form-row">
        <div class="form-group col-md-6">
            <label>{{ form.gender.label }}</label>
            {{ form.gender(class="form-control") }}
            {% for error in form.gender.errors %}
                <span style="color: red; ">[{{ error }}]</span>
            {% endfor %}
        </div>
        <div class="form-group col-md-6">
                <label>{{ form.age_group.label }}</label>
                {{ form.age_group(class="form-control") }}
                {% for error in form.age_group.errors %}
                    <span style="color: red; ">[{{ error }}]</span>
                {% endfor %}
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label>{{ form.nationality.label }}</label>
            {{ form.nationality(class="form-control") }}
            {% for error in form.nationality.errors %}
                <span style="color: red; ">[{{ error }}]</span>
            {% endfor %}
    </div>
    <div class="form-group col-md-6">
            <label>{{ form.latest_country.label }}</label>
            {{ form.latest_country(class="form-control") }}
            <small class="form-text text-muted">
                This is the country you have lived in most in the last 10 years.
            </small>
            {% for error in form.latest_country.errors %}
                <span style="color: red; ">[{{ error }}]</span>
            {% endfor %}
    </div>
    </div>
    <div class="form-row">

    <div class="form-group col-md-6">
            <label>{{ form.education_level.label }}</label>
            {{ form.education_level(class="form-control") }}
            <small class="form-text text-muted">
                For more information on your education level please <a href="https://www.gov.uk/what-different-qualification-levels-mean/list-of-qualification-levels">visit the Government website</a>
            </small>
            {% for error in form.education_level.errors %}
                <span style="color: red; ">[{{ error }}]</span>
            {% endfor %}
        </div>
    <div class="form-group col-md-6">
        <label>{{ form.occupation.label }}</label>
        {{ form.occupation(class="form-control") }}
        {% for error in form.occupation.errors %}
            <span style="color: red; ">[{{ error }}]</span>
        {% endfor %}
    </div>
    </div>
    <div class="form-row">
    <div class="form-group col-md-3">
        <label>{{ form.income.label }}</label>
        {{ form.income(class="form-control") }}
        <small class="form-text text-muted">
            Income per anum.
        </small>
        {% for error in form.income.errors %}
            <span style="color: red; ">[{{ error }}]</span>
        {% endfor %}
    </div>
    </div>
    
    <p>{{ form.submit(class="btn btn-primary") }}</p>
    </form>

app/templates/study/study.html
{% extends "base.html" %}

{% block head %}
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/board.css') }}">
    <script src="{{ url_for('static', filename='js/process_cards.js') }}"></script>
    <script src="https://unpkg.com/@popperjs/core@2"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(function () {
            $('[data-toggle="tooltip"]').tooltip()
        })
    </script>
{% endblock %}

{% block table %}
<div class="row">
    <div class="col">
        <h3>{{ study.card_set_y.name }}</h3>
        <p class="text-muted">Place these cards along the Y axis of the table below.</p>
        <div id="sortable-container-y" class="droptrue2 d-flex flex-wrap">
            {% for card in card_set_y.cards %}
            <div>
                <div card_id="{{card.id}}" class="card">
                    {% if card.image %}
                        <img class="card-img-top img" src="{{ url_for('static', filename='img/card_images/'~creator_id~'/'+card.image) }}" alt="Card Image">
                    {% endif %}
                    <div class="card-body">
                        {% if card.description %}
                            <p class="card-text title description" data-toggle="tooltip" data-placement="top" title="{{ card.description }}">{{ card.name }}</p>       
                        {% else %}
                            <p class="card-text title">{{ card.name }}</p>
                        {% endif %}
                    </div>
                </div>
            </div>  
            {% endfor %}
        </div>
    </div>
</div>

<div class="row">
<div class="col">
<div id="card-table" class="table-responsive">
 <table class="table table-bordered">
    {% for row in range(0, study.number_of_rows) %}
    {% set outer_loop = loop %}


        <tr>
            <td style="border:none;" row="row_{{ study.number_of_rows-outer_loop.index }}" class="sortable-y droptrue2 cards-row">
              
            </td>
        
            {% if loop.index0 == 0%}
                <td style="border:none; vertical-align:middle">
                    <p>Highest {{ card_set_y.measure}} </p>
                </td>
            {% elif loop.index0 == study.number_of_rows-1 %}
                <td style="border:none; vertical-align:middle">
                    <p>Lowest {{ card_set_y.measure }}</p>
                </td>
            {% else %}
                <td style="border:none;"></td>
            {% endif%}
            
            
            {% for column in range(0, study.number_of_columns) %}
            
                <td class="data-values" style="vertical-align: middle;" col-row="col_{{ loop.index0 }}_row_{{ study.number_of_rows-outer_loop.index }}">
                  
                    {% for label in study.data_value_labels %}
                        <form>
                            <div class="form-group data-value">
                                <label label_id="{{ label.id }}" >{{ label.label }}</label>
                                <input type="number" class="value form-control form-control-sm">    
                            </div>
                        </form>
                    {% endfor %}
            
                </td>
            {% endfor %}
        </tr>
    {% endfor %}
    <tr>
        <td style="border: none;">
        </td>
        <td style="border:none;">
        </td>
        
        {% for col in range(0, study.number_of_columns) %}
        {% if loop.index0==0 %}
            <td style="border:none; text-align:center;">
                Lowest {{ card_set_x.measure }}
            </td>
        {% elif loop.index0 == study.number_of_columns-1 %}
            <td style="border:none; text-align:center;">
                Highest {{ card_set_x.measure }}
            </td>
        {% else %}
            <td style="border:none;"></td>
        {% endif %}
        {% endfor %}
    </tr>
    <tr>
        <td style="border: none;">
        </td>
        <td style="border: none;">
        </td>
        
        {% for col in range(0, study.number_of_columns) %}
        {% set outer_loop = loop %}
            <td style="border:none;" col="col_{{ outer_loop.index0 }}" class="sortable-x droptrue1 cards-col">
            
            </td>
        {% endfor %}
    </tr>
    
 </table>
 </div>
 </div>
 </div>
 <div class="row">
    <div class="col">
        <h3>{{ study.card_set_x.name }}</h3>
        <p class="text-muted">Place these cards along the X axis of the table above.</p>
        <div id="sortable-container-x" class="droptrue1 d-flex flex-wrap">
            {% for card in card_set_x.cards %}
            <div>
                    <div card_id="{{ card.id }}" class="card">
                    {% if card.image %}
                        <img class="card-img-top img" src="{{ url_for('static', filename='img/card_images/'~creator_id~'/'+card.image) }}" alt="Card Image">
                    {% endif %}        
                        <div class="card-body">
                            {% if card.description %}
                                <p class="card-text title description" data-toggle="tooltip" data-placement="top" title="{{ card.description }}">{{ card.name }}</p>       
                            {% else %}
                                <p class="card-text title">{{ card.name }}</p>
                            {% endif %}
                        </div>
                    </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

<a id="submit" class="btn btn-primary text-white" url="{{ url_for('study.study', id=study.id )}}" csrf="{{ csrf_token() }}">Submit</a>
{% endblock %}

app/templates/study/user_info.html
{% extends "base3.html" %}

{% block content %}
<div class="row h-100 justify-content-center align-items-center">
    <div class="card">
            <div class="card-body">
                {% with messages = get_flashed_messages() %}
                    {% if messages %}
                    <div class="alert alert-primary" role="alert">
                            {% for message in messages %}
                                {{ message }}
                            {% endfor %}
                    </div>
                    {% endif %}
                {% endwith %}

                <h3>Hey!</h3>
                <p>Welcome to the IoT Data Trading Survey platform. shortly you will be participating in survey about
                    how willing you would be to sell your data and at what cost.</p>
                    <hr class="my-4">
                    <p>First, we are going to ask you to fill out some data about yourselves.</p>
                    {% include "study/info_form_base.html" %}

                </div>
            
        </div>
    </div>
{% endblock %}